apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "restarter.stackable.tech"
webhooks:
- name: "restarter.stackable.tech"
  rules:
  - apiGroups:   ["apps"]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["statefulsets"]
    scope:       "Namespaced"
  clientConfig:
    url: https://192.168.1.147:9766/restarter/webhook
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
  failurePolicy: Fail
