apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  labels:
    restarter.stackable.tech/enabled: "true"
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: registry.k8s.io/nginx-slim:0.24
          ports:
          - containerPort: 80
            name: web
          volumeMounts:
          - name: config
            mountPath: "/config"
          envFrom:
          - configMapRef:
              name: web-config-2
      volumes:
        - name: config
          configMap:
            name: web-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  foo: bar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config-2
data:
  foo: bar
