apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  labels:
spec:
  replicas: 10000
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo
        image: busybox
