---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commons-operator-deployment
  labels:
    stackable.tech/vendor: Stackable
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: commons-operator
      app.kubernetes.io/instance: commons-operator
      stackable.tech/vendor: Stackable
  template:
    metadata:
      annotations:
        internal.stackable.tech/image: docker.stackable.tech/stackable/commons-operator:0.0.0-dev
      labels:
        app.kubernetes.io/name: commons-operator
        app.kubernetes.io/instance: commons-operator
        stackable.tech/vendor: Stackable
    spec:
      serviceAccountName: commons-operator-serviceaccount
      containers:
        - name: commons-operator
          image: docker.stackable.tech/stackable/commons-operator:0.0.0-dev
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 1024Mi
          volumeMounts:
            - mountPath: /etc/stackable/commons-operator/config-spec
              name: config-spec
          env:
            - name: OPERATOR_IMAGE
              # Tilt can use annotations as image paths, but not env variables
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['internal.stackable.tech/image']
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: cluster.local
      volumes:
        - name: config-spec
          configMap:
            name: commons-operator-configmap
