---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commons-operator-clusterrole
  labels:
    app.kubernetes.io/instance: commons-operator
    app.kubernetes.io/name: commons-operator
    app.kubernetes.io/version: 0.0.0-dev
    stackable.tech/vendor: Stackable
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - secrets
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - patch # We need to add a label to the StatefulSet
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
