---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: commons-operator-serviceaccount
  labels:
    app.kubernetes.io/instance: commons-operator
    app.kubernetes.io/name: commons-operator
    app.kubernetes.io/version: 0.0.0-dev
    stackable.tech/vendor: Stackable
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: commons-operator-clusterrolebinding
  labels:
    app.kubernetes.io/instance: commons-operator
    app.kubernetes.io/name: commons-operator
    app.kubernetes.io/version: 0.0.0-dev
    stackable.tech/vendor: Stackable
subjects:
  - kind: ServiceAccount
    name: commons-operator-serviceaccount
    namespace: stackable-operators
roleRef:
  kind: ClusterRole
  name: commons-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
