= Installation
:description: Install the Stackable Commons Operator with either stackablectl or Helm.

== Prerequisites

You will need:

* a Kubernetes cluster
* kubectl
* Helm

Resource sizing depends on cluster type(s), usage and scope, but as a starting point we recommend a minimum of the following resources for this operator:

* 0.2 cores (e.g. i5 or similar)
* 256MB RAM

== Installation

There are two ways to deploy the Commons operator into your Kubernetes cluster.

. Using xref:management:stackablectl:index.adoc[].
. Using Helm.

[tabs]
====
stackablectl::
+
--
`stackablectl` is the recommended command line tool to install and manage with Stackable operators.
Follow the xref:management:stackablectl:installation.adoc[installation steps] for your platform.

After you have installed `stackablectl`, use it to install the Commons Operator:

[source,console]
$ stackablectl operator install commons=24.7.0

The tool will show:

[source]
Installed commons=24.7.0 operator

TIP: Consult the xref:management:stackablectl:quickstart.adoc[] to learn more about how to use `stackablectl`. For
example, you can use the `--cluster kind` flag to create a Kubernetes cluster with link:https://kind.sigs.k8s.io/[kind].
--

Helm::
+
--
Helm allows you to download and deploy Stackable operators on Kubernetes.

NOTE: `helm repo` subcommands are not supported for OCI registries. The operators are installed directly, without adding the Helm Chart repository first.

Install the Stackable Commons Operator

[source,console]
$ helm install --wait commons-operator \
  oci://oci.stackable.tech/sdp-charts/commons-operator --version 24.7.0

Helm will deploy the operator in Kubernetes and apply the CRDs.
--
====
