= Pod enricher
:description: Use Labels to instruct the Stackable Commons Operator to enrich Pods with Kubernetes node addresses

WARNING: The pod enricher is deprecated as of the Stackable Data Platform 24.11, and will be removed in the next release. For more information, see https://github.com/stackabletech/commons-operator/issues/292[issue #292].

The Stackable Commons Operator automatically adds commonly used information to Pod objects, which would otherwise have to be inferred by traversing the Kubernetes object graph.

== Usage

To enable the pod enricher for a Pod, set the label `enrichment.stackable.tech/enabled` to `true`.

== Which information is added to the Pod?

Annotation:: `enrichment.stackable.tech/node-address`

The hostname or IP address of the Node that the Pod is scheduled to run on.
Compared to `Pod.status.nodeIP`, this can also (but doesn't have to) be a hostname, and prefers externally routable addresses.

This is intended to be used for components that need to register an accessible address (such as Kafka brokers, or HDFS DataNodes).
