= Restarter
:description: Automatically restart Pods or StatefulSets using Stackable Commons Operator based on expiration dates or stale configurations.

The Stackable Commons Operator can automatically restart Pod objects based on certain criteria.
This can be applied to either the Pod or certain controller objects (such as StatefulSet).

== Pod

Pods are evicted when any of their restart criteria (listed below) expire, with the expectation that their owning controller is then responsible for restarting them.

Because they are evicted rather than deleted, this process should respect PodDisruptionBudget constraints, allowing users to ensure that clusters are restarted gracefully.

=== Expiration date

Annotation:: `restarter.stackable.tech/expires-at.\{tag\}`

Pods can be configured to expire at a certain point in time.
In this case, the Pod should have the annotation `restarter.stackable.tech/expires-at.\{tag\}` set to a datetime formatted according to RFC 3339 (such as `"2022-04-21T13:24:15.225774724+00:00"`).
`\{tag\}` should be a deterministic but unique ID identifying the reason for the expiry.

Multiple `expires-at` annotations can be set on the same Pod, in which case the *earliest* expiration datetime takes precedence.

== StatefulSet

StatefulSets are rolling-restarted when any of their restart criteria (listed below) expire.

=== Stale configuration

Label:: `restarter.stackable.tech/enabled`

The operator can restart StatefulSets when any referenced configuration object (ConfigMap or Secret) changes.
To enable this, set the `restarter.stackable.tech/enabled` label on the StatefulSet to `true`.

Annotation:: `restarter.stackable.tech/ignore`

If a resource is only used for initialization or is hot-reloaded and should not trigger a restart, add the annotation `restarter.stackable.tech/ignore: "true"` to the corresponding ConfigMap or Secret:

[source,yaml]
----
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-with-enabled-restarter
  labels:
    restarter.stackable.tech/enabled: "true"
spec:
  template:
    spec:
      volumes:
        - name: hot-reloaded-configmap
          configMap:
            name: hot-reloaded-configmap
        - name: hot-reloaded-secret
          secret:
            secretName: hot-reloaded-secret
...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hot-reloaded-configmap
  annotations:
    restarter.stackable.tech/ignore: "true"
...
---
apiVersion: v1
kind: Secret
metadata:
  name: hot-reloaded-secret
  annotations:
    restarter.stackable.tech/ignore: "true"
...
----
