= `AuthenticationClass`

`AuthenticationClass` is a CRD describing a generic authentication method like LDAP or Kerberos.
Multiple operators use this CRD as a way to express the authentication of the product.

At the moment the following Authentication providers are supported:

* <<LDAP>>

== LDAP
A very simple `AuthenticationClass` with LDAP Authentication looks like this:

[source,yaml]
----
include::example$authenticationclass-ldap-simple.yaml[]
----
<1> The hostname of the LDAP server without any protocol or port
<2> The port of the LDAP server. If TLS is used it defaults to `636` otherwise to `389`
<3> An optional searchBase where the users should be searched

=== OpenLDAP
Here is an example that is tuned for an OpenLDAP LDAP server:

[source,yaml]
----
include::example$authenticationclass-ldap-openldap-simple.yaml[]
----
<1> The name of the xref:secret-operator::secretclass.adoc[] providing the bind credentials (username and password). Must match the name of the xref:secret-operator::secretclass.adoc[] in this example in ②
<2> The name of the xref:secret-operator::secretclass.adoc[]
<3> Search for a `Secret` in the namespace the product will run in
<4> The `Secret` containing the actual bind credentials. Please keep in mind that the `Secret` needs to be in the same namespace as the product
<5> The name of the xref:secret-operator::secretclass.adoc[] that wants to refer to this `Secret`. Must match the name of the xref:secret-operator::secretclass.adoc[] in this example in ②

=== All possible attributes
The following example shows all possible attributes:

[source,yaml]
----
include::example$authenticationclass-ldap-full.yaml[]
----
<1> The hostname of the LDAP server without any protocol or port
<2> The port of the LDAP server. If TLS is used defaults to `636` otherwise to `389`
<3> The searchBase where the users should be searched
<4> Additional filter that filters the allowed users
<5> The name of the corresponding field names in the LDAP objects
<6> The name of the xref:secret-operator::secretclass.adoc[] providing the bind credentials (username and password)
<7> The xref:secret-operator::scope.adoc[] of the xref:secret-operator::secretclass.adoc[]
<8> xref:tls.adoc[] connection to the LDAP server
